"""empty message

Revision ID: 170973613d13
Revises: 5eae75984030
Create Date: 2017-11-27 16:33:26.185000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170973613d13'
down_revision = '5eae75984030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
